### ISSUE TITLE
História 4: Implementação dos Endpoints da API

### ISSUE THREAD

**Issue by Pjmaciel** [Pjmaciel/Projeto-Estagio-Back-End-Api#13]
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#21 
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#22
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#23
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#24 
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#25
