### ISSUE TITLE
História 2: Criação dos Modelos

### ISSUE THREAD

**Issue by Pjmaciel** [Pjmaciel/Projeto-Estagio-Back-End-Api#5]
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#17 
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#6 
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#18 
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#19 
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#20
