### ISSUE TITLE
História 3: Implementação de Autenticação

### ISSUE THREAD

**Issue by Pjmaciel** [Pjmaciel/Projeto-Estagio-Back-End-Api#7]
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#8 
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#9
- [x] Pjmaciel/Projeto-Estagio-Back-End-Api#10
